### ISSUE TITLE
会话列表问题

### ISSUE THREAD

**Issue by zhangzhanzg** [easemob/hyphenate-cocoapods#15]
退出登录再登录后，通过getAllConversations获取不到会话列表，而登录后再次自动登录后就能正常获取会话列表，弃用的loadAllConversationsFromDB则没有这个问题。3.2.2.2版本

**Comment by lizilong1989** [comment]
@zhangzhanzg 我测试3.2.2.2调用getAllConversations这个方法没有出现你说的这种情况. 
登录->调用getAllConversations->登出->再登录->调用getAllConversations
两次调用getAllConversations都能够获取到会话列表

**Comment by zhangzhanzg** [comment]
非常感谢，我登录成功后看log状态是登录状态，也连接这服务器，可是调用getAllConversations一直获取不到数据，而换成loadAllConversationsFromDB就可以获取，是登录后还需要做其他处理么？
