### ISSUE TITLE
pod install 之后，无法编译。

### ISSUE THREAD

**Issue by nealwangzi** [easemob/hyphenate-cocoapods#5]
<img width="237" alt="1" src="https://cloud.githubusercontent.com/assets/13897181/15773957/64ca8100-29ac-11e6-94e5-d798106cd702.png">
之前版本都是一个总的.a 静态库，希望可以解决下，谢谢

**Comment by lizilong1989** [comment]
@nealwangzi 现在已经合成一个.a了
