### ISSUE TITLE
警告很多，能否用 clang++ 编译以去除警告？

### ISSUE THREAD

**Issue by exherb** [easemob/hyphenate-cocoapods#9]
![2016-09-21 12 50 16](https://cloud.githubusercontent.com/assets/65154/18698160/75f23d2a-7ffa-11e6-8c2f-c0803ac464e5.png)

**Comment by xilin** [comment]
+1 警告看着很烦啊

**Comment by lizilong1989** [comment]
@xilin @exherb SDK 3.2.1 已经去掉了这些warning
